// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkfdkgixlgsdpqxpsrsf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprZmRrZ2l4bGdzZHBxeHBzcnNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc5OTk0NjIsImV4cCI6MjA1MzU3NTQ2Mn0.LPcXEMbHF36h_0AH0iCO9uqFBNANUj0qscXuYRTpuGo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);